import Head from "next/head"
import styles from "./MainLayout.module.css";
import { Navbar } from "..";
import { Inter } from 'next/font/google'
import Link from "next/link";
const inter = Inter({ subsets: ['latin'] })
 const MainLayout = ({ children }: { children: React.ReactNode}) => {
    return (
        <>
          <Head>
            <title>Hello World</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar/>
          <main className={`${styles.main} ${inter.className}`}>
            {children}
          </main>
        </>
      )
    
}

export default MainLayout;
